[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
cache_path = "cache"
solc = "0.8.30"
optimizer = true
optimizer_runs = 1
via_ir = true
fs_permissions = [{ access = "read", path = "./test/vectors" }]
remappings = [
    "filecoin-pay/=lib/filecoin-pay/src/",
    "@openzeppelin/contracts/=lib/filecoin-pay/lib/openzeppelin-contracts/contracts/",
    "fvm-solidity/=lib/filecoin-pay/lib/fvm-solidity/src/",
    "forge-std/=lib/filecoin-pay/lib/forge-std/src/",
    "@prb-math/=lib/filecoin-pay/lib/prb-math/src/",
]
